### ISSUE TITLE
Redirect URI doesn't match your registered redirect URIs - ORCID

### ISSUE THREAD

**Issue by SteveViss** [mangal-wg/orcid-oauth2#8]
I have an issue on the ORCID authentification server. 

Get this error from the ORCID production server: `Redirect URI doesn't match your registered redirect URIs.`
Pretty sure that the callback URI registered on the server match to the one registered in the client APP.

I suspect that the server is not refreshing the cache instantaneously which result to this error.

**Comment by SteveViss** [comment]
Fixed by refreshing app credential on ORCID server

**Comment by nlovte** [comment]
This issue popped up again today. I got the redirection working fine and after two trials it starts showing the message "Redirect URI doesn't match your registered redirect URIs". The URI is same as what it was before.
